### ISSUE TITLE
DNS or site issue

### ISSUE THREAD

**Issue by DavidKozdra** [0ME9A/password#51]
**Describe the bug**
The site or DNS resolution appears to be down

**To Reproduce**

go to https://password.ome9a.com/

**Expected behavior**
our normal app being visible 

**Screenshots**
![image](https://github.com/0ME9A/password/assets/45106564/c98e00cd-b150-44cb-812c-ffb356fb491b)

**Desktop (please complete the following information):**
Brave 
Linux

**Comment by 0ME9A** [comment]
Hi @DavidKozdra,

Thank you for reporting the issue regarding the site or DNS resolution being down. This was due to a domain renewal issue on our side. The domain issue has been fixed, and the site should now be accessible as usual.

Please let us know if you encounter any further issues.

![image](https://github.com/0ME9A/password/assets/83957658/4a240177-2013-44f6-831f-b99f8cb4a62a)

**Comment by DavidKozdra** [comment]
awesome glad its working again
